version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  node: bigcommerce/internal-node@volatile

jobs:
  build:
    executor:
      name: node/node
      node-version: '20.19'
    steps:
      - ci/pre-setup
      - ci/merge-base
      - restore_cache:
          keys:
            - data-store
      - run: npm ci
      - save_cache:
          key: data-store
          paths:
            - ~/.npm
      - run:
          name: 'Test'
          command: 'npm run test'
          when: always
      - run:
          name: 'Lint'
          command: 'npm run lint'
          when: always
